source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecsMirror.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0' 
target 'BeerNotesRN' do
pod 'YWFeedbackFMWK', '~> 2.0.3.1'  
pod 'TWMessageBarManager'
#标准SDK，含IDFA
pod 'UMengAnalytics'
pod 'IQKeyboardManager'
pod 'Bugly'
pod 'AFNetworking', '~> 3.0'
end
